[versions]
agp = "8.13.0"
kotlin = "2.2.20"
compose = "1.9.0"
retain = "1.10.0-rc01"
mavenPublish = "0.34.0"
uiTooling = "1.9.5"

[libraries]
compose-runtime-retain = { module = "androidx.compose.runtime:runtime-retain", version.ref = "retain" }
jetbrains-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose" }
compose-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "uiTooling" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "uiTooling" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
